/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Returns the current selection text. If there is no selection text, returns an empty string.
 *
 * The selection text is retrieved through a 6-step process:
 * 1. Save clipboard existing text or image
 * 2. Clear clipboard
 * 3. Simulate `Ctrl + C` (`Cmd + C` in Mac) keyboard input to copy selection text to clipboard
 * 4. Poll clipboard to retrieve selection text in a loop every 1ms. The loop breaks if the
 *    selection text is found or it times out after 80ms by default
 * 5. Restore clipboard previous text or image to minimize side effects to users
 * 6. Return selection text as the result
 *
 * ##### Arguments
 * * `timeOutMs` - An optional number that sets the max time to wait for selection text to
 *                 appear in the clipboard during clipboard polling. Default to 80ms. Can be
 *                 adjusted lower or higher depending on OS and use case. Smaller selection text
 *                 is faster to copy while larger selection text takes longer.
 * * `printTimeToCopy` - An optional boolean that if set to true, print the time taken to copy
 *                       selection text to clipboard to console. Default to false. Useful for
 *                       debugging and adjusting `timeOutMs`.
 */
export declare function getSelectionText(timeOutMs?: number | undefined | null, printTimeToCopy?: boolean | undefined | null): string
/**
 * Simulate `Ctrl + C` (`Cmd + C` in Mac) keyboard input to copy selection text to clipboard
 *
 * Useful for those who would like to implement custom logics to save and restore clipboard state
 * or just want to perform copy
 *
 * As for implementation, Windows calls into Enigo to simulate keyboard input. But for Mac, it calls
 * into Mac's Core Graphics CGEvent library directly to work around 2 issues with Enigo's current
 * implementation, which causes additional delay (https://github.com/enigo-rs/enigo/issues/105)
 * and subjects to mouse movement/keyboard interruption (https://github.com/enigo-rs/enigo/issues/201).
 * Calling into CGEvent and setting event flag solves both issues.
 */
export declare function copy(): void
